org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.paths=\
  C:\\Java\\GraalVM\\17,\
  C:\\Java\\GraalVM\\25+37.1,\
  C:\\Java\\Dragonwell\\8

mod.id=ccb
mod.name=CCB Mod
mod.group=org.infpancakefactory.ccb.mod
mod.version=1.0.0

display.url=https://s.jerrya.top/
display.authors=r_Jerry_
display.description_base=Changed Clean Break! Mod
display.license=AGPL-3.0-or-later
display.license_text=GNU Affero General Public License 3.0 or later
display.issues_track=https://github.com/0x724a/ccb/issues
display.update_json_url=
display.credits=

deps.fabric-loader=0.19.0
deps.fabric-kotlin=1.13.4+kotlin.2.2.0
deps.kotlinforforge=5.9.0
deps.mixinsquared=0.3.7-beta.1
deps.conditional=0.6.4

deps.parchment=[V]
deps.createrailwaynagivator=[V]
deps.create=[V]
deps.ponder=[V]
deps.flywheel=[V]
deps.registrate=[V]
deps.dragonlib=[V]

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.forge=[VERSIONED]

deps.modmenu=[VERSIONED]

publish.additionalVersions=[VERSIONED]

publish.modrinth=4Y5tAszO
publish.curseforge=1399840
#publish.additionalVersions=