modLoader="javafml"
loaderVersion="[47,)"
license="${license}"
issueTrackerURL="${issues_track}"

[[mods]]
modId="${modid}"
version="${version}"
displayName="${modname}"
updateJSONURL="${update_json_url}"
displayURL="${displayurl}"
logoFile="icon.png"
credits="${credits}"
authors="${authors}"
description='''
${description}\nLicense under ${license_text}
'''

[[dependencies.${modid}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.${modid}]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"